#!/bin/bash

# exist script if any command fails
set -o errexit
# exist script if any pipe command fails
set -o pipefail
# exist script if any variable is not set
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# func that checks the availability of the DB
postgres_ready() {
python << END
import sys
import psycopg2

try:
   psycopg2.connect(
      dbname="${POSTGRES_DB}",
      user="${POSTGRES_USER}",
      password="${POSTGRES_PASSWORD}",
      host="${POSTGRES_HOST}",
      port="${POSTGRES_PORT}",
   )
except psycopg2.OperationalError:
   sys.exit(-1)

sys.exit(0)
END
}

# until the db is available output this ....
until postgres_ready; do
>&2 echo "************* Waiting for PostgreSQL to become available.... ************* :-("
sleep 1
done
>&2 echo "************* PostgreSQL is ready!!!!..... ************* :-)"

exec "$@"