# Generated by Django 3.2.12 on 2022-04-24 15:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=12, region=None, verbose_name='phone number'),
        ),
    ]
